services:
  - type: web
    name: lumina-skincare-assistant
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: ASSISTANT_ID
        sync: false 